-- FOR SHOW LIST OF ENGINES
SHOW ENGINES;

-- FOR SHOW TABLES
SHOW TABLES;

-- CREATE TABLE
CREATE TABLE barang(
    id INT NOT NULL,
    name VARCHAR(100) NOT NULL,
    harga INT NOT NULL DEFAULT 0,
    jumlah INT NOT NULL DEFAULT 0
) ENGINE = InnoDB;

-- SHOW STRUCTURE OF TABLE
DESCRIBE barang;
DESC barang;

-- SHOW STRUCTURE OF TABLE WITH SQL QUERY
SHOW CREATE TABLE barang;

-- UPDATE STRUCTURE OF TABLE
ALTER TABLE barang
    ADD COLUMN nama_column TEXT, -- ADD NEW COLUMN
    DROP COLUMN name, -- DELETE COLUMN
    RENAME COLUMN name to nama_baru, -- RENAME COLUMN
    MODIFY nama VARCHAR(100) AFTER jumlah, -- UPDATE DATA TYPE OF COLUMN
    MODIFY nama VARCHAR(100) FIRST;

ALTER TABLE barang
    ADD COLUMN deskripsi TEXT;

-- ERROR
-- ALTER TABLE barang
--     RENAME COLUMN name TO nama;

ALTER TABLE barang
    ADD COLUMN salah TEXT;

ALTER TABLE barang
    DROP COLUMN salah;

ALTER TABLE barang
    MODIFY name VARCHAR(200) AFTER deskripsi;

ALTER TABLE barang
    MODIFY name VARCHAR(200) FIRST;

-- NOT NULL
ALTER TABLE barang
    MODIFY id INT NOT NULL FIRST,
    MODIFY name VARCHAR(200) NOT NULL AFTER id;

-- DEFAULT VALUE
ALTER TABLE barang
    MODIFY harga INT NOT NULL DEFAULT 0 AFTER deskripsi,
    MODIFY jumlah INT NOT NULL DEFAULT 0 AFTER harga;

ALTER TABLE barang
ADD COLUMN waktu_dibuat TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- DELETE ALL DATA/ROW IN TABLE
TRUNCATE barang;

-- DELETE TABLE
DROP table barang;